"""update model

Revision ID: fa0913a802c2
Revises: c19fc3d2b246
Create Date: 2025-07-20 08:46:56.171445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa0913a802c2'
down_revision: Union[str, Sequence[str], None] = 'c19fc3d2b246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_tags',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.create_index(op.f('ix_posts_tags_created_at'), 'posts_tags', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_tags_post_id'), 'posts_tags', ['post_id'], unique=False)
    op.create_index(op.f('ix_posts_tags_tag_id'), 'posts_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_posts_tags_updated_at'), 'posts_tags', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_tags_updated_at'), table_name='posts_tags')
    op.drop_index(op.f('ix_posts_tags_tag_id'), table_name='posts_tags')
    op.drop_index(op.f('ix_posts_tags_post_id'), table_name='posts_tags')
    op.drop_index(op.f('ix_posts_tags_created_at'), table_name='posts_tags')
    op.drop_table('posts_tags')
    # ### end Alembic commands ###
